runtime: python38
service: 'bn-api'
handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  GOOGLE_CLOUD_PROJECT: 'beauty-now-313716'
  USE_CLOUD_SQL_AUTH_PROXY: 'true'
