# Generated by Django 3.2.5 on 2021-08-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffassignment',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn_app.lineitem'),
        ),
    ]
