# Generated by Django 3.2.2 on 2021-05-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0002_auto_20210213_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='place_id',
        ),
        migrations.AddField(
            model_name='workorder',
            name='place_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
