# Generated by Django 3.2.5 on 2021-08-24 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0002_alter_staffassignment_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffline',
            name='auth_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffline',
            name='pay_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
