# Generated by Django 3.2.2 on 2021-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0003_auto_20210513_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='status',
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(default='initial_request', max_length=32),
        ),
    ]
