# Generated by Django 3.2.7 on 2021-10-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_as_html',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_as_html',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
