# Generated by Django 3.2.7 on 2021-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='address',
            field=models.JSONField(null=True),
        ),
    ]
