# Generated by Django 3.2.7 on 2021-10-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0002_alter_workorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='address',
            field=models.JSONField(default=dict),
        ),
    ]
