# Generated by Django 3.2.7 on 2021-10-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0002_auto_20211005_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name_as_html',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='name_as_html',
        ),
    ]
