# Generated by Django 3.1.14 on 2022-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bn_app", "0003_beautierprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="beautierprofile",
            name="title",
            field=models.CharField(default="Maquillista", max_length=64),
            preserve_default=False,
        ),
    ]
