# Generated by Django 3.2.7 on 2021-12-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0003_alter_workorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
