# Generated by Django 3.1.14 on 2022-06-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0004_beautierprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautierprofile',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
