# Generated by Django 4.0.6 on 2022-07-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bn_app', '0009_remove_service_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('country_code', models.CharField(max_length=3)),
                ('state_province_code', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='ServicePublicPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bn_app.region')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn_app.service')),
            ],
            options={
                'verbose_name_plural': 'Service Public Prices',
            },
        ),
        migrations.CreateModel(
            name='ServicePayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bn_app.region')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn_app.service')),
            ],
            options={
                'verbose_name_plural': 'Service Payouts',
            },
        ),
        migrations.CreateModel(
            name='ServiceInternalCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bn_app.region')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bn_app.service')),
            ],
            options={
                'verbose_name_plural': 'Service Internal Costs',
            },
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('code', 'country_code', 'state_province_code'), name='unique_region '),
        ),
    ]
