# Generated by Django 3.1.6 on 2021-02-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_now_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='place_id',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='place_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
