# Generated by Django 3.1.2 on 2020-10-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_now_app', '0002_auto_20200527_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beautierprofile',
            name='availability',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='service',
            name='availability',
            field=models.JSONField(),
        ),
    ]
